services:
  postgres:
    image: postgres:16-alpine
    container_name: editorial_db
    restart: always
    environment:
      POSTGRES_DB: editorial_db
      POSTGRES_USER: editorial_user
      POSTGRES_PASSWORD: editorial_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: editorial_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@editorial.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    container_name: weaviate_db
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'

  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'

volumes:
  postgres_data:
